### Importing the necessary libraries

In [60]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor


from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor


from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    root_mean_squared_error,
    r2_score
)


import joblib

### Load dataset

In [61]:
df = pd.read_csv('Clean_Data_Boston.csv')

In [62]:
df.head()

   ID  indus  chas    nox     rm   age     dis  rad  tax  ptratio  lstat  medv
0   1   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   4.98  24.0
1   2   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   9.14  21.6
2   4   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   2.94  33.4
3   5   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   5.33  36.2
4   7   7.87     0  0.524  6.012  66.6  5.5605    5  311     15.2  12.43  22.9

### Splitting the data for input and output

In [63]:
x = df.drop(columns = 'medv') #Spliting the inputs 
x.head()

y = df['medv'] #Spliting the output 
y.head()

0    24.0
1    21.6
2    33.4
3    36.2
4    22.9
Name: medv, dtype: float64

In [64]:
x.head()

   ID  indus  chas    nox     rm   age     dis  rad  tax  ptratio  lstat
0   1   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   4.98
1   2   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   9.14
2   4   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   2.94
3   5   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   5.33
4   7   7.87     0  0.524  6.012  66.6  5.5605    5  311     15.2  12.43

In [65]:
num_col = x.columns

### Splitting the data for the training and tsting

In [66]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)

In [67]:
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((266, 11), (67, 11), (266,), (67,))

### Transformation

In [68]:
num_features = x.select_dtypes(include=["int64", "float64"]).columns
cat_features = x.select_dtypes(include=["object"]).columns

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), num_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features)
    ]
)

### Training Models

### Linear Regression

In [69]:
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LinearRegression())
])

In [70]:
#Training the model 
pipeline.fit(X_train,Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', LinearRegression())])

In [71]:
y_pred = pipeline.predict(X_test)

In [72]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred),
    "MSE": mean_squared_error(Y_test, y_pred),
    "RMSE": root_mean_squared_error(Y_test, y_pred),
    "R2_Score": r2_score(Y_test, y_pred)
}

In [73]:

joblib.dump(metrics, "Linear_Metrics.pkl")

['Linear_Metrics.pkl']

In [74]:
print(metrics)

{'MAE': 3.5910332380298278, 'MSE': 24.052893551163972, 'RMSE': 4.904374939904572, 'R2_Score': 0.7274641342886978}

In [75]:

mae = mean_absolute_error(Y_test, y_pred)
mse = mean_squared_error(Y_test, y_pred)
rmse = root_mean_squared_error(Y_test, y_pred)
r2 = r2_score(Y_test, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R2   : {r2:.4f}")

MAE  : 3.59
MSE  : 24.05
RMSE : 4.90
R2   : 0.7275

In [76]:
House_1 = pd.DataFrame({

    "Unnamed: 0": [506],
    "ID": [507],
    "indus": [5.19],
    "chas": [0],
    "nox": [0.53],
    "rm": [6.50],
    "age": [60.5],
    "dis": [4.25],
    "rad": [5],
    "tax": [280],
    "ptratio": [16.5],
    "lstat": [8.20]

})

In [77]:
pipeline.predict(House_1)

array([26.26885761])

In [78]:
joblib.dump(pipeline,"Linear_Model.pkl")

['Linear_Model.pkl']

### Decision Tree Regressor

In [79]:
pipeline_DT = Pipeline([
    ("preprocessing", preprocessor),
    ("model", DecisionTreeRegressor())
])

In [80]:
pipeline_DT.fit(X_train,Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', DecisionTreeRegressor())])

In [81]:
y_pred_dt = pipeline_DT.predict(X_test)

In [82]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_dt),
    "MSE": mean_squared_error(Y_test, y_pred_dt),
    "RMSE": root_mean_squared_error(Y_test, y_pred_dt),
    "R2_Score": r2_score(Y_test, y_pred_dt)
}
print(metrics)

{'MAE': 3.220895522388059, 'MSE': 17.68059701492537, 'RMSE': 4.204830200486741, 'R2_Score': 0.7996666470291609}

In [83]:

mae = mean_absolute_error(Y_test, y_pred_dt)
mse = mean_squared_error(Y_test, y_pred_dt)
rmse = root_mean_squared_error(Y_test, y_pred_dt)
r2 = r2_score(Y_test, y_pred_dt)

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R2   : {r2:.4f}")

MAE  : 3.22
MSE  : 17.68
RMSE : 4.20
R2   : 0.7997

In [84]:
joblib.dump(metrics, "DT_Metrics.pkl")

['DT_Metrics.pkl']

In [85]:
joblib.dump(pipeline_DT,"DT_Model.pkl")

['DT_Model.pkl']

### Random Forest

In [86]:
pipeline_RF = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100,random_state=42))
])

In [87]:
pipeline_RF.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', RandomForestRegressor(random_state=42))])

In [88]:
y_pred_rf = pipeline_RF.predict(X_test)

In [89]:

mae = mean_absolute_error(Y_test, y_pred_rf)
mse = mean_squared_error(Y_test, y_pred_rf)
rmse = root_mean_squared_error(Y_test, y_pred_rf)
r2 = r2_score(Y_test, y_pred_rf)

print(f"MAE  : {mae:.2f}")
print(f"MSE  : {mse:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R2   : {r2:.4f}")

MAE  : 2.43
MSE  : 10.40
RMSE : 3.22
R2   : 0.8822

In [90]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_rf),
    "MSE": mean_squared_error(Y_test, y_pred_rf),
    "RMSE": root_mean_squared_error(Y_test, y_pred_rf),
    "R2_Score": r2_score(Y_test, y_pred_rf)
}
print(metrics)

{'MAE': 2.4319552238805957, 'MSE': 10.39520882089551, 'RMSE': 3.2241601729590776, 'R2_Score': 0.8822151177268474}

In [91]:
joblib.dump(metrics,"RF_Metrics.pkl")

['RF_Metrics.pkl']

In [92]:
joblib.dump(pipeline_RF,"RF_Model.pkl")

['RF_Model.pkl']

### SVM

In [93]:
pipeline_SVM = Pipeline([
    ("preprocessing", preprocessor),
    ("model", SVR(
        kernel='rbf',
        C=1.0,
        gamma='scale'
    ))
])

In [94]:
pipeline_SVM.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', SVR())])

In [95]:
y_pred_svm = pipeline_SVM.predict(X_test)

In [96]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_svm),
    "MSE": mean_squared_error(Y_test, y_pred_svm),
    "RMSE": root_mean_squared_error(Y_test, y_pred_svm),
    "R2_Score": r2_score(Y_test, y_pred_svm)
}
print(metrics)

{'MAE': 3.434038903319594, 'MSE': 29.098402077561108, 'RMSE': 5.394293473436638, 'R2_Score': 0.670295044371495}

In [97]:
joblib.dump(metrics,"SVM_Metrics.pkl")

['SVM_Metrics.pkl']

In [98]:
joblib.dump(pipeline_SVR,"SVM_Model.pkl")

['SVM_Model.pkl']

### KNN

In [99]:
pipeline_KNN = Pipeline([
    ("preprocessing", preprocessor),
    ("model", KNeighborsRegressor(
        n_neighbors=5,
        weights='uniform',
        metric='minkowski',
        p=2
    ))
])

In [100]:
pipeline_KNN.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', KNeighborsRegressor())])

In [101]:
y_pred_knn = pipeline_KNN.predict(X_test)

In [102]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_knn),
    "MSE": mean_squared_error(Y_test, y_pred_knn),
    "RMSE": root_mean_squared_error(Y_test, y_pred_knn),
    "R2_Score": r2_score(Y_test, y_pred_knn)
}
print(metrics)

{'MAE': 2.7979104477611942, 'MSE': 15.519050746268652, 'RMSE': 3.9394226412342013, 'R2_Score': 0.8241584563971397}

In [103]:
joblib.dump(metrics,"KNN_Metrics.pkl")

['KNN_Metrics.pkl']

In [104]:
joblib.dump(pipeline_KNN,"KNN_Model.pkl")

['KNN_Model.pkl']

### Gradient Boosting

In [105]:
pipeline_GB = Pipeline([
    ("preprocessing", preprocessor),
    ("model", GradientBoostingRegressor(
        n_estimators=100,
        learning_rate=0.1,
        max_depth=3,
        min_samples_split=2,
        min_samples_leaf=1,
        subsample=1.0,
        random_state=42
    ))
])

In [106]:
pipeline_GB.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model', GradientBoostingRegressor(random_state=42))])

In [107]:
y_pred_GB = pipeline_GB.predict(X_test)

In [108]:

print("MAE :", mean_absolute_error(Y_test, y_pred_GB))
print("MSE :", mean_squared_error(Y_test, y_pred_GB))
print("RMSE:", root_mean_squared_error(Y_test, y_pred_GB))
print("R2 Score:", r2_score(Y_test, y_pred_GB))

MAE : 2.3642186925877757
MSE : 9.604793854532485
RMSE: 3.099160185361913
R2 Score: 0.8911710641983475

In [109]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_GB),
    "MSE": mean_squared_error(Y_test, y_pred_GB),
    "RMSE": root_mean_squared_error(Y_test, y_pred_GB),
    "R2_Score": r2_score(Y_test, y_pred_GB)
}
print(metrics)

{'MAE': 2.3642186925877757, 'MSE': 9.604793854532485, 'RMSE': 3.099160185361913, 'R2_Score': 0.8911710641983475}

In [110]:
joblib.dump(metrics, "GB_Metrics.pkl")

['GB_Metrics.pkl']

In [111]:
joblib.dump(pipeline_GB, "GB_Model.pkl")

['GB_Model.pkl']

### Ada Boosting

In [112]:
pipeline_AB = Pipeline([
    ("preprocessing", preprocessor),
    ("model", AdaBoostRegressor(
        n_estimators=100,
        learning_rate=1.0,
        loss='linear',
        random_state=42
    ))
])

In [113]:
pipeline_AB.fit(X_train, Y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['ID', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat'],
      dtype='object')),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  Index([], dtype='object'))])),
                ('model',
                 AdaBoostRegressor(n_estimators=100, random_state=42))])

In [114]:
y_pred_AB = pipeline_AB.predict(X_test)

In [115]:
print("MAE :", mean_absolute_error(Y_test, y_pred_AB))
print("MSE :", mean_squared_error(Y_test, y_pred_AB))
print("RMSE:", root_mean_squared_error(Y_test, y_pred_AB))
print("R2 Score:", r2_score(Y_test, y_pred_AB))

MAE : 2.901636173168717
MSE : 13.631908977421626
RMSE: 3.692141516440239
R2 Score: 0.8455410736111004

In [116]:
metrics = {
    "MAE": mean_absolute_error(Y_test, y_pred_AB),
    "MSE": mean_squared_error(Y_test, y_pred_AB),
    "RMSE": root_mean_squared_error(Y_test, y_pred_AB),
    "R2_Score": r2_score(Y_test, y_pred_AB)
}
print(metrics)

{'MAE': 2.901636173168717, 'MSE': 13.631908977421626, 'RMSE': 3.692141516440239, 'R2_Score': 0.8455410736111004}

In [117]:

joblib.dump(metrics, "AB_Metrics.pkl")

['AB_Metrics.pkl']

In [118]:

joblib.dump(pipeline_AB, "AB_Model.pkl")

['AB_Model.pkl']